"""added_user_uploads

Revision ID: 97bcc02e788d
Revises: 31fe82d336d1
Create Date: 2026-05-04 14:36:05.345182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97bcc02e788d'
down_revision: Union[str, None] = '31fe82d336d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_inventory_user_id'), 'inventory', ['user_id'], unique=False)
    op.create_foreign_key('fk_inventory_user_id_users', 'inventory', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_inventory_user_id_users', 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_user_id'), table_name='inventory')
    op.drop_column('inventory', 'user_id')
    # ### end Alembic commands ###
